<#
.SYNOPSIS
  Writes skypipe\.env and skypipe\terraform\terraform.tfvars from your GCP project ID.
  Picks a random globally-unique bucket name unless you pass -BucketName.

.EXAMPLE
  .\scripts\Configure-SkyPipe.ps1 -ProjectId "my-gcp-project-123"

.EXAMPLE
  Local-only (Docker / uvicorn without GCS):
  .\scripts\Configure-SkyPipe.ps1 -LocalOnly
#>
param(
    [string] $ProjectId = "",
    [string] $BucketName = "",
    [switch] $LocalOnly
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")

function Write-EnvFile {
    param(
        [string] $Proj,
        [string] $Bucket,
        [string] $KeyPath
    )
    $keyLine = if ($KeyPath) { $KeyPath } else { "" }
    @"
# Generated by Configure-SkyPipe.ps1

ADMIN_USERNAME=admin
ADMIN_PASSWORD=skypipe
JWT_SECRET=skypipe-change-me-to-random-secret

GCP_PROJECT=$Proj
GCS_BUCKET=$Bucket

SPARK_MASTER=local[*]

GOOGLE_APPLICATION_CREDENTIALS=$keyLine

CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080

S3_ENDPOINT=
S3_ACCESS_KEY=
S3_SECRET_KEY=
S3_BUCKET=skypipe-uploads
S3_USE_SSL=false
"@ | Set-Content -Path (Join-Path $Root ".env") -Encoding utf8
}

if ($LocalOnly) {
    New-Item -ItemType Directory -Force -Path (Join-Path $Root "credentials") | Out-Null
    Write-EnvFile -Proj "" -Bucket "" -KeyPath ""
    Write-Host "OK: Local-only .env written (GCP_PROJECT and GCS_BUCKET empty)."
    Write-Host "Next: cd '$Root'; docker compose up --build"
    exit 0
}

if (-not $ProjectId) {
    $ProjectId = Read-Host "Enter your GCP Project ID (e.g. from console.cloud.google.com)"
}
if (-not $ProjectId) {
    Write-Host "No project ID. Use -LocalOnly or pass -ProjectId."
    exit 1
}

if (-not $BucketName) {
    $suffix = [guid]::NewGuid().ToString("N").Substring(0, 12)
    $BucketName = "skypipe-$suffix"
    Write-Host "Using bucket name: $BucketName (change in terraform.tfvars if you prefer another)."
}

$tfvars = @"
# Generated by Configure-SkyPipe.ps1

project_id  = "$ProjectId"
region      = "us-central1"
bucket_name = "$BucketName"
bq_dataset  = "skypipe"

create_dataproc_cluster = false
"@
$tfvars | Set-Content -Path (Join-Path $Root "terraform\terraform.tfvars") -Encoding utf8

$credDir = Join-Path $Root "credentials"
New-Item -ItemType Directory -Force -Path $credDir | Out-Null
$keyFile = Join-Path $credDir "skypipe-sa.json"

Write-EnvFile -Proj $ProjectId -Bucket $BucketName -KeyPath $keyFile

Write-Host ""
Write-Host "========== DONE =========="
Write-Host "Files updated:"
Write-Host "  $Root\.env"
Write-Host "  $Root\terraform\terraform.tfvars"
Write-Host ""
Write-Host "Run these in order (copy from RUN.txt if you prefer):"
Write-Host ""
Write-Host "  1) Log in for Terraform (one-time per machine; opens browser):"
Write-Host "     gcloud auth application-default login"
Write-Host "     gcloud config set project $ProjectId"
Write-Host ""
Write-Host "  2) cd `"$Root\terraform`""
Write-Host "     terraform init"
Write-Host "     terraform apply"
Write-Host ""
Write-Host "  3) After apply succeeds, get the service account email:"
Write-Host "     terraform output -raw service_account_email"
Write-Host ""
Write-Host "  4) Create the key file for the Python/Docker app:"
Write-Host "     gcloud iam service-accounts keys create `"$keyFile`" --iam-account=PASTE_EMAIL_HERE --project=$ProjectId"
Write-Host ""
Write-Host "  5) Key file path (docker-compose mounts it in the API container):"
Write-Host "     $keyFile"
Write-Host ""
Write-Host "  6) Start the app (React UI on http://localhost:8080 , API on :8000):"
Write-Host "     cd `"$Root`""
Write-Host "     docker compose up --build"
Write-Host ""
